name: Build Snapshot

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      jars: ${{ steps.list.outputs.jars }}

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 25

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Build with Gradle
      run: ./gradlew build

    - name: List jars
      id: list
      run: echo "jars=$(cd build/libs && ls *.jar | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  upload:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jar: ${{ fromJson(needs.build.outputs.jars) }}

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: all-jars

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.jar }}
        path: ${{ matrix.jar }}
